https://github.com/sihsieh65-tech/cs82a-portfolio/upload/main/Module3

Loading data from the bridges.csv file and running basic .shape, .info(), .describe() and .isna()sum() functions.

In [1]:
import pandas as pd
df = pd.read_csv('bridges.csv')
df

,Id,river,location,erected,purpose,length,lanes,clear-g,t-or-d,material,span,rel-l,type
0,E1,M,3.0,1818,HIGHWAY,NaN,2.0,N,THROUGH,WOOD,SHORT,S,WOOD
1,E2,A,25.0,1819,HIGHWAY,1037.0,2.0,N,THROUGH,WOOD,SHORT,S,WOOD
2,E3,A,39.0,1829,AQUEDUCT,NaN,1.0,N,THROUGH,WOOD,NaN,S,WOOD
3,E5,A,29.0,1837,HIGHWAY,1000.0,2.0,N,THROUGH,WOOD,SHORT,S,WOOD
4,E6,M,23.0,1838,HIGHWAY,NaN,2.0,N,THROUGH,WOOD,NaN,S,WOOD
...,...,...,...,...,...,...,...,...,...,...,...,...,...
103,E84,A,24.0,1969,HIGHWAY,870.0,6.0,G,THROUGH,STEEL,MEDIUM,F,ARCH
104,E91,O,44.0,1975,HIGHWAY,3756.0,6.0,G,THROUGH,STEEL,LONG,F,ARCH
105,E90,M,7.0,1978,HIGHWAY,950.0,6.0,G,THROUGH,STEEL,LONG,F,ARCH
106,E100,O,43.0,1982,HIGHWAY,NaN,NaN,G,NaN,NaN,NaN,F,NaN
107,E109,A,28.0,1986,HIGHWAY,NaN,NaN,G,NaN,NaN,NaN,F,NaN

In [2]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 108 entries, 0 to 107
Data columns (total 13 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Id        108 non-null    str
 1   river     108 non-null    str
 2   location  107 non-null    float64
 3   erected   108 non-null    int64
 4   purpose   108 non-null    str
 5   length    81 non-null     float64
 6   lanes     92 non-null     float64
 7   clear-g   106 non-null    str
 8   t-or-d    102 non-null    str
 9   material  106 non-null    str
 10  span      92 non-null     str
 11  rel-l     103 non-null    str
 12  type      106 non-null    str
dtypes: float64(3), int64(1), str(9)
memory usage: 11.1 KB

In [3]:
df.shape

(108, 13)

In [4]:
df.isna().sum()

Id           0
river        0
location     1
erected      0
purpose      0
length      27
lanes       16
clear-g      2
t-or-d       6
material     2
span        16
rel-l        5
type         2
dtype: int64

In [5]:
df.describe()

         location      erected       length      lanes
count  107.000000   108.000000    81.000000  92.000000
mean    25.978505  1905.314815  1567.469136   2.630435
std     13.665871    37.173664   747.491523   1.164657
min      1.000000  1818.000000   804.000000   1.000000
25%     15.500000  1884.000000  1000.000000   2.000000
50%     27.000000  1903.000000  1300.000000   2.000000
75%     37.500000  1928.000000  2000.000000   4.000000
max     52.000000  1986.000000  4558.000000   6.000000

For the purposes of this exercise I would flag any length greater than the average length plus the standard deviation to be suspicious. Therefore, I would want to examine any lengths greater than 2315 ft.

In [6]:
df[df["length"]>2315]

,Id,river,location,erected,purpose,length,lanes,clear-g,t-or-d,material,span,rel-l,type
31,E34,O,41.0,1888,RR,4558.0,2.0,G,THROUGH,STEEL,LONG,F,SIMPLE-T
41,E42,M,9.0,1895,HIGHWAY,2367.0,2.0,G,THROUGH,STEEL,LONG,F,SIMPLE-T
44,E46,A,37.0,1897,RR,4000.0,2.0,G,DECK,STEEL,LONG,F,SIMPLE-T
52,E87,A,35.0,1903,RR,3000.0,2.0,G,THROUGH,STEEL,MEDIUM,S,SIMPLE-T
65,E61,O,41.0,1915,RR,2822.0,2.0,G,THROUGH,STEEL,LONG,F,SIMPLE-T
71,E66,A,32.0,1924,HIGHWAY,2365.0,4.0,G,THROUGH,STEEL,MEDIUM,S,ARCH
76,E72,M,5.0,1927,HIGHWAY,2663.0,4.0,N,DECK,STEEL,MEDIUM,S-F,CANTILEV
78,E75,A,30.0,1928,HIGHWAY,2678.0,4.0,G,DECK,STEEL,MEDIUM,F,ARCH
95,E81,M,14.0,1951,HIGHWAY,2423.0,4.0,G,DECK,STEEL,LONG,F,CONT-T
104,E91,O,44.0,1975,HIGHWAY,3756.0,6.0,G,THROUGH,STEEL,LONG,F,ARCH

Applying the same logic in the reverse I would want to look at any bridges shorter then the average minus the standard deviaion, which would mean examining all data where length was shorter than 820ft.

In [7]:
df[df["length"]<820]

,Id,river,location,erected,purpose,length,lanes,clear-g,t-or-d,material,span,rel-l,type
98,E82,O,42.0,1955,HIGHWAY,804.0,NaN,G,THROUGH,STEEL,NaN,F,SIMPLE-T

Ultimately I decided to leave the flagged values in the dataset unchanged. While these example are outside the standard deviation from the average, they are no impossible nor even improbable to be real values. There is no indication any data was misrecorded.