https://github.com/sihsieh65-tech/cs82a-portfolio/tree/main/Module4

Import the dataset. I corrected the data in vs code to match the data in the textbook as the csv provided had zeros for the area in rows 7-14. The edited csv file will be uploaded with the rest of the lab.

In [1]:
import pandas as pd
df = pd.read_csv('allbacks.csv')
df

    rownames  volume  area  weight cover
0          1     885   382     800    hb
1          2    1016   468     950    hb
2          3    1125   387    1050    hb
3          4     239   371     350    hb
4          5     701   371     750    hb
5          6     641   367     600    hb
6          7    1228   396    1075    hb
7          8     412   257     250    pb
8          9     953   300     700    pb
9         10     929   301     650    pb
10        11    1492   403     975    pb
11        12     419   213     350    pb
12        13    1010   432     950    pb
13        14     595   262     425    pb
14        15    1034   380     725    pb

Determining the median cover type by sorting first, then locating the value in the middle of the sorted list. The median cover type was determined to be paperback. This however, has little meaning in context of this analysis. The median value is easily verified as there are only two values and one of them is present exactly one more time than the other leading to a odd number of values. In such a situation the value that is represented one additional time will always be the median value.

In [2]:
sorted_strings = df['cover'].sort_values().reset_index(drop=True)
mid_index = len(sorted_strings) // 2
median_string = sorted_strings.iloc[mid_index]
print("Median string:", median_string)

Median string: pb

Checking the median and mean of the book volumes, areas, and weights. Of note, I feel that area and volume are meant to provide similar information with regards to how much space each book occupies by cover type. In our 3-dimensional world, the volume is the more meaningful value and therefore we will prioritize that over the area. As such further analysis will not be done using the area. The overall average weight of books in this library is 706.7 grams which is pretty close to the median weight of 725.0 g.

In [3]:
df['volume'].median(), df['area'].median(), df['weight'].median()

(np.float64(929.0), np.float64(371.0), np.float64(725.0))

In [4]:
df['volume'].mean(), df['area'].mean(), df['weight'].mean()

(np.float64(845.2666666666667),
 np.float64(352.6666666666667),
 np.float64(706.6666666666666))

Calculating the average, median, max and mininmum weights and volumes of the books, grouped by cover type. Based on the grouped means the hardback books weigh notably more than paperback books on average.

In [5]:
df.groupby('cover').agg(
    average_weight=('weight', 'mean'),
    median_weight=('weight','median'),
    max_weight=('weight', 'max'),
    min_weight=('weight', 'min')
).reset_index()

  cover  average_weight  median_weight  max_weight  min_weight
0    hb      796.428571          800.0        1075         350
1    pb      628.125000          675.0         975         250

In [6]:
df.groupby('cover').agg(
    average_volume=('volume', 'mean'),
    median_volume=('volume','median'),
    max_volume=('volume', 'max'),
    min_volume=('volume', 'min')
).reset_index()

  cover  average_volume  median_volume  max_volume  min_volume
0    hb      833.571429          885.0        1228         239
1    pb      855.500000          941.0        1492         412

Based on the data I choose to use the median as a basis for comparison as the paperback books show a bit of a skew in the average weight and an even larger skew in the average volume. Based on the median values and assuming I am choosing which cover type to choose based on how to most fully stock my library I would select hardcover books. Since hard coverbooks have a notably smaller median volume I should be able to fit more books than if I chose to stock paperback books.  

However, much of the prompts for this lab focus on the mean weights. If we are basing our decisions on the weights of the average paperback vs the average hardcover I would imagine the goal would be to end up with the lighter average set of books as this would make stocking and moving books around easier. Based on that logic, I would choose to stock paperback books over hardcover as they are lighter on average than the hardcovers. I do note that the average weight of paperback books differs significantly from the median weight and therefore is perhaps not the most reliable measure to use, but it is the one specified in the prompts.